### ISSUE TITLE
Subscription plan at the logo title changes when you navigate from Mailbox to Settings

### ISSUE THREAD

**Issue by dhoko** [ProtonMail/protonmail-settings#66] opened 2019-07-12 13:36 UTC
- [ ] Subscription plan at the logo title changes when you navigate from Mailbox to Settings
http://g.recordit.co/KaAMEaE1nd.gif

_Originally posted by @nikolanol in https://github.com/ProtonMail/Angular/pull/8922#issuecomment-510852981_

Edit:
Settings App is wrong cf my plans
```json
{
  "Code": 1000,
  "Subscription": {
    "ID": "28yfeU10iuUrclaiXQ5QeBi61dO9xH6CFDtt4Opvu7uxxtdt7Do6SpMLUJsq1ad73jAHODg8b9KM2KGyUGkLbw==",
    "InvoiceID": "ttcwIOKaY5vMxke4bGXQ7L42jT-D8DQ3meXTcifsrdFfXfTp7VNZyLlnzQ6P6qkBd2ShYGsWXkFo_P0UPOI_QQ==",
    "Cycle": 12,
    "PeriodStart": 1551266821,
    "PeriodEnd": 1582802821,
    "Currency": "EUR",
    "Amount": 19680,
    "Plans": [
      {
        "ID": "1H8EGg3J1QpSDL6K8hGsTvwmHXdtQvnxplUMePE7Hruen5JsRXvaQ75-sXptu03f0TCO-he3ymk0uhrHx6nnGQ==",
        "Type": 0,
        "Name": "1member",
        "Title": "+1 User",
        "MaxDomains": 0,
        "MaxAddresses": 5,
        "MaxSpace": 5368709120,
        "MaxMembers": 1,
        "MaxVPN": 0,
        "Services": 1,
        "Features": 0,
        "Cycle": 12,
        "Currency": "EUR",
        "Amount": 7500,
        "Quantity": 1
      },
      {
        "ID": "S6oNe_lxq3GNMIMFQdAwOOk5wNYpZwGjBHFr5mTNp9aoMUaCRNsefrQt35mIg55iefE3fTq8BnyM4znqoVrAyA==",
        "Type": 1,
        "Name": "vpnplus",
        "Title": "ProtonVPN Plus",
        "MaxDomains": 0,
        "MaxAddresses": 0,
        "MaxSpace": 0,
        "MaxMembers": 0,
        "MaxVPN": 5,
        "Services": 4,
        "Features": 0,
        "Cycle": 12,
        "Currency": "EUR",
        "Amount": 9600,
        "Quantity": 1
      },
      {
        "ID": "j_hMLdlh76xys5eR2S3OM9vlAgYylGQBiEzDeXLw1H-huHy2jwjwVqcKAPcdd6z2cXoklLuQTegkr3gnJXCB9w==",
        "Type": 1,
        "Name": "professional",
        "Title": "ProtonMail Professional",
        "MaxDomains": 2,
        "MaxAddresses": 10,
        "MaxSpace": 5368709120,
        "MaxMembers": 1,
        "MaxVPN": 0,
        "Services": 1,
        "Features": 1,
        "Cycle": 12,
        "Currency": "EUR",
        "Amount": 7500,
        "Quantity": 1
      }
    ]
  }
}
```

**Comment by mmso** [comment] 2019-08-02 20:04
Duplicate of https://github.com/ProtonMail/react-components/issues/131

**Closed by mmso** 2019-08-02 20:04 UTC
Labels: bug
